Args = -H:+ReportExceptionStackTraces \
       -H:IncludeResources=seed/customers.json \
       -H:IncludeResources=static/.vite/manifest.json \
       -H:IncludeResources=git.properties \
       -H:IncludeResources=META-INF/build-info.properties
